package com.example.apppruebasfisicas.pantallaDetallePrueba

fun calcularNota(nombrePrueba: String, resultado: Float, edad: Int, sexo: String): String {
    return when (nombrePrueba) {
        "Abdominales" -> calcularNotaAbdominales(resultado, edad, sexo)
        "Flexibilidad" -> calcularNotaFlexibilidad(resultado, edad, sexo)
        "Test de Cooper" -> calcularNotaTestCooper(resultado, edad, sexo)
        "Velocidad 5x10" -> calcularNotaVelocidad(resultado, edad, sexo)
        "Lanzamiento de Balon" -> calcularNotaLanzamiento(resultado, edad, sexo)
        else -> "N/A"
    }
}

fun calcularNotaAbdominales(resultado: Float, edad: Int, sexo: String): String {
    return when (sexo) {
        "Chico" -> when (edad) {
            12 -> when {
                resultado >= 30 -> "10"
                resultado >= 29 -> "9.5"
                resultado >= 28 -> "9"
                resultado >= 27 -> "8.5"
                resultado >= 26 -> "8"
                resultado >= 25 -> "7.5"
                resultado >= 24 -> "7"
                resultado >= 23 -> "6.5"
                resultado >= 22 -> "6"
                resultado >= 21 -> "5.5"
                resultado >= 20 -> "5"
                resultado >= 19 -> "4.5"
                resultado >= 18 -> "4"
                resultado >= 17 -> "3.5"
                resultado >= 16 -> "3"
                resultado >= 15 -> "2.5"
                resultado >= 14 -> "2"
                else -> "N/A"
            }
            13 -> when {
                resultado >= 32 -> "10"
                resultado >= 31 -> "9.5"
                resultado >= 30 -> "9"
                resultado >= 29 -> "8.5"
                resultado >= 28 -> "8"
                resultado >= 27 -> "7.5"
                resultado >= 26 -> "7"
                resultado >= 25 -> "6.5"
                resultado >= 24 -> "6"
                resultado >= 23 -> "5.5"
                resultado >= 22 -> "5"
                resultado >= 21 -> "4.5"
                resultado >= 20 -> "4"
                resultado >= 19 -> "3.5"
                resultado >= 18 -> "3"
                resultado >= 17 -> "2.5"
                resultado >= 16 -> "2"
                else -> "N/A"
            }
            14 -> when {
                resultado >= 33 -> "10"
                resultado >= 32 -> "9.5"
                resultado >= 31 -> "9"
                resultado >= 30 -> "8.5"
                resultado >= 29 -> "8"
                resultado >= 28 -> "7.5"
                resultado >= 27 -> "7"
                resultado >= 26 -> "6.5"
                resultado >= 25 -> "6"
                resultado >= 24 -> "5.5"
                resultado >= 23 -> "5"
                resultado >= 22 -> "4.5"
                resultado >= 21 -> "4"
                resultado >= 20 -> "3.5"
                resultado >= 19 -> "3"
                resultado >= 18 -> "2.5"
                resultado >= 17 -> "2"
                else -> "N/A"
            }
            15 -> when {
                resultado >= 36 -> "10"
                resultado >= 35 -> "9.5"
                resultado >= 34 -> "9"
                resultado >= 33 -> "8.5"
                resultado >= 32 -> "8"
                resultado >= 31 -> "7.5"
                resultado >= 30 -> "7"
                resultado >= 29 -> "6.5"
                resultado >= 28 -> "6"
                resultado >= 27 -> "5.5"
                resultado >= 26 -> "5"
                resultado >= 25 -> "4.5"
                resultado >= 24 -> "4"
                resultado >= 23 -> "3.5"
                resultado >= 22 -> "3"
                resultado >= 21 -> "2.5"
                resultado >= 20 -> "2"
                else -> "N/A"
            }
            16 -> when {
                resultado >= 38 -> "10"
                resultado >= 37 -> "9.5"
                resultado >= 36 -> "9"
                resultado >= 35 -> "8.5"
                resultado >= 34 -> "8"
                resultado >= 33 -> "7.5"
                resultado >= 32 -> "7"
                resultado >= 31 -> "6.5"
                resultado >= 30 -> "6"
                resultado >= 29 -> "5.5"
                resultado >= 28 -> "5"
                resultado >= 27 -> "4.5"
                resultado >= 26 -> "4"
                resultado >= 25 -> "3.5"
                resultado >= 24 -> "3"
                resultado >= 23 -> "2.5"
                resultado >= 22 -> "2"
                else -> "N/A"
            }
            else -> "N/A"
        }

        "Chica" -> when (edad) {
            12 -> when {
                resultado >= 30 -> "10"
                resultado >= 29 -> "9.5"
                resultado >= 28 -> "9"
                resultado >= 27 -> "8.5"
                resultado >= 26 -> "8"
                resultado >= 25 -> "7.5"
                resultado >= 24 -> "7"
                resultado >= 23 -> "6.5"
                resultado >= 22 -> "6"
                resultado >= 21 -> "5.5"
                resultado >= 20 -> "5"
                resultado >= 19 -> "4.5"
                resultado >= 18 -> "4"
                resultado >= 17 -> "3.5"
                resultado >= 16 -> "3"
                resultado >= 15 -> "2.5"
                resultado >= 14 -> "2"
                else -> "N/A"
            }
            13 -> when {
                resultado >= 32 -> "10"
                resultado >= 31 -> "9.5"
                resultado >= 30 -> "9"
                resultado >= 29 -> "8.5"
                resultado >= 28 -> "8"
                resultado >= 27 -> "7.5"
                resultado >= 26 -> "7"
                resultado >= 25 -> "6.5"
                resultado >= 24 -> "6"
                resultado >= 23 -> "5.5"
                resultado >= 22 -> "5"
                resultado >= 21 -> "4.5"
                resultado >= 20 -> "4"
                resultado >= 19 -> "3.5"
                resultado >= 18 -> "3"
                resultado >= 17 -> "2.5"
                resultado >= 16 -> "2"
                else -> "N/A"
            }
            14 -> when {
                resultado >= 33 -> "10"
                resultado >= 32 -> "9.5"
                resultado >= 31 -> "9"
                resultado >= 30 -> "8.5"
                resultado >= 29 -> "8"
                resultado >= 28 -> "7.5"
                resultado >= 27 -> "7"
                resultado >= 26 -> "6.5"
                resultado >= 25 -> "6"
                resultado >= 24 -> "5.5"
                resultado >= 23 -> "5"
                resultado >= 22 -> "4.5"
                resultado >= 21 -> "4"
                resultado >= 20 -> "3.5"
                resultado >= 19 -> "3"
                resultado >= 18 -> "2.5"
                resultado >= 17 -> "2"
                else -> "N/A"
            }
            15 -> when {
                resultado >= 35 -> "10"
                resultado >= 34 -> "9.5"
                resultado >= 33 -> "9"
                resultado >= 32 -> "8.5"
                resultado >= 31 -> "8"
                resultado >= 30 -> "7.5"
                resultado >= 29 -> "7"
                resultado >= 28 -> "6.5"
                resultado >= 27 -> "6"
                resultado >= 26 -> "5.5"
                resultado >= 25 -> "5"
                resultado >= 24 -> "4.5"
                resultado >= 23 -> "4"
                resultado >= 22 -> "3.5"
                resultado >= 21 -> "3"
                resultado >= 20 -> "2.5"
                resultado >= 19 -> "2"
                else -> "N/A"
            }
            16 -> when {
                resultado >= 37 -> "10"
                resultado >= 36 -> "9.5"
                resultado >= 35 -> "9"
                resultado >= 34 -> "8.5"
                resultado >= 33 -> "8"
                resultado >= 32 -> "7.5"
                resultado >= 31 -> "7"
                resultado >= 30 -> "6.5"
                resultado >= 29 -> "6"
                resultado >= 28 -> "5.5"
                resultado >= 27 -> "5"
                resultado >= 26 -> "4.5"
                resultado >= 25 -> "4"
                resultado >= 24 -> "3.5"
                resultado >= 23 -> "3"
                resultado >= 22 -> "2.5"
                resultado >= 21 -> "2"
                else -> "N/A"
            }
            else -> "N/A"
        }
        else -> "N/A"
    }
}

fun calcularNotaFlexibilidad(resultado: Float, edad: Int, sexo: String): String {
    return when (sexo) {
        "Chico" -> when (edad) {
            12 -> when {
                resultado >= 7 -> "10"
                resultado >= 5 -> "9.5"
                resultado >= 3 -> "9"
                resultado >= 1 -> "8.5"
                resultado >= 0 -> "8"
                resultado >= -1 -> "7.5"
                resultado >= -2 -> "7"
                resultado >= -4 -> "6.5"
                resultado >= -6 -> "6"
                resultado >= -8 -> "5.5"
                resultado >= -10 -> "5"
                resultado >= -12 -> "4.5"
                resultado >= -14 -> "4"
                resultado >= -16 -> "3.5"
                resultado >= -18 -> "3"
                resultado >= -20 -> "2.5"
                resultado >= -22 -> "2"
                else -> "N/A"
            }
            13 -> when {
                resultado >= 12 -> "10"
                resultado >= 10 -> "9.5"
                resultado >= 8 -> "9"
                resultado >= 6 -> "8.5"
                resultado >= 4 -> "8"
                resultado >= 3 -> "7.5"
                resultado >= 2 -> "7"
                resultado >= 1 -> "6.5"
                resultado >= 0 -> "6"
                resultado >= -2 -> "5.5"
                resultado >= -4 -> "5"
                resultado >= -6 -> "4.5"
                resultado >= -8 -> "4"
                resultado >= -10 -> "3.5"
                resultado >= -12 -> "3"
                resultado >= -14 -> "2.5"
                resultado >= -16 -> "2"
                else -> "N/A"
            }
            14 -> when {
                resultado >= 13 -> "10"
                resultado >= 11 -> "9.5"
                resultado >= 9 -> "9"
                resultado >= 7 -> "8.5"
                resultado >= 5 -> "8"
                resultado >= 3 -> "7.5"
                resultado >= 1 -> "7"
                resultado >= 0 -> "6.5"
                resultado >= -1 -> "6"
                resultado >= -3 -> "5.5"
                resultado >= -5 -> "5"
                resultado >= -7 -> "4.5"
                resultado >= -9 -> "4"
                resultado >= -11 -> "3.5"
                resultado >= -13 -> "3"
                resultado >= -15 -> "2.5"
                resultado >= -17 -> "2"
                else -> "N/A"
            }
            15, 16 -> when {
                resultado >= 15 -> "10"
                resultado >= 13 -> "9.5"
                resultado >= 11 -> "9"
                resultado >= 9 -> "8.5"
                resultado >= 7 -> "8"
                resultado >= 5 -> "7.5"
                resultado >= 4 -> "7"
                resultado >= 3 -> "6.5"
                resultado >= 2 -> "6"
                resultado >= 1 -> "5.5"
                resultado >= 0 -> "5"
                resultado >= -2 -> "4.5"
                resultado >= -4 -> "4"
                resultado >= -6 -> "3.5"
                resultado >= -8 -> "3"
                resultado >= -10 -> "2.5"
                resultado >= -12 -> "2"
                else -> "N/A"
            }
            else -> "N/A"
        }

        "Chica" -> when (edad) {
            12 -> when {
                resultado >= 7 -> "10"
                resultado >= 5 -> "9.5"
                resultado >= 3 -> "9"
                resultado >= 1 -> "8.5"
                resultado >= 0 -> "8"
                resultado >= -1 -> "7.5"
                resultado >= -2 -> "7"
                resultado >= -4 -> "6.5"
                resultado >= -6 -> "6"
                resultado >= -8 -> "5.5"
                resultado >= -10 -> "5"
                resultado >= -12 -> "4.5"
                resultado >= -14 -> "4"
                resultado >= -16 -> "3.5"
                resultado >= -18 -> "3"
                resultado >= -20 -> "2.5"
                resultado >= -22 -> "2"
                else -> "N/A"
            }
            13 -> when {
                resultado >= 12 -> "10"
                resultado >= 10 -> "9.5"
                resultado >= 8 -> "9"
                resultado >= 6 -> "8.5"
                resultado >= 4 -> "8"
                resultado >= 3 -> "7.5"
                resultado >= 2 -> "7"
                resultado >= 1 -> "6.5"
                resultado >= 0 -> "6"
                resultado >= -2 -> "5.5"
                resultado >= -4 -> "5"
                resultado >= -6 -> "4.5"
                resultado >= -8 -> "4"
                resultado >= -10 -> "3.5"
                resultado >= -12 -> "3"
                resultado >= -14 -> "2.5"
                resultado >= -16 -> "2"
                else -> "N/A"
            }
            14, 15, 16 -> when {
                resultado >= 17 -> "10"
                resultado >= 15 -> "9.5"
                resultado >= 13 -> "9"
                resultado >= 11 -> "8.5"
                resultado >= 9 -> "8"
                resultado >= 7 -> "7.5"
                resultado >= 5 -> "7"
                resultado >= 4 -> "6.5"
                resultado >= 3 -> "6"
                resultado >= 2 -> "5.5"
                resultado >= 1 -> "5"
                resultado >= 0 -> "4.5"
                resultado >= -2 -> "4"
                resultado >= -4 -> "3.5"
                resultado >= -6 -> "3"
                resultado >= -8 -> "2.5"
                resultado >= -10 -> "2"
                else -> "N/A"
            }
            else -> "N/A"
        }
        else -> "N/A"
    }
}

fun calcularNotaTestCooper(resultado: Float, edad: Int, sexo: String): String {
    return when (sexo) {
        "Chico" -> when (edad) {
            12 -> when {
                resultado >= 2600 -> "10"
                resultado >= 2400 -> "9.5"
                resultado >= 2200 -> "9"
                resultado >= 2100 -> "8.5"
                resultado >= 2000 -> "8"
                resultado >= 1950 -> "7.5"
                resultado >= 1900 -> "7"
                resultado >= 1850 -> "6.5"
                resultado >= 1800 -> "6"
                resultado >= 1750 -> "5.5"
                resultado >= 1700 -> "5"
                resultado >= 1650 -> "4.5"
                resultado >= 1600 -> "4"
                resultado >= 1550 -> "3.5"
                resultado >= 1500 -> "3"
                resultado >= 1450 -> "2.5"
                resultado >= 1400 -> "2"
                else -> "N/A"
            }
            13 -> when {
                resultado >= 2650 -> "10"
                resultado >= 2475 -> "9.5"
                resultado >= 2300 -> "9"
                resultado >= 2200 -> "8.5"
                resultado >= 2100 -> "8"
                resultado >= 2050 -> "7.5"
                resultado >= 2000 -> "7"
                resultado >= 1950 -> "6.5"
                resultado >= 1900 -> "6"
                resultado >= 1850 -> "5.5"
                resultado >= 1800 -> "5"
                resultado >= 1750 -> "4.5"
                resultado >= 1700 -> "4"
                resultado >= 1650 -> "3.5"
                resultado >= 1600 -> "3"
                resultado >= 1550 -> "2.5"
                resultado >= 1500 -> "2"
                else -> "N/A"
            }
            14 -> when {
                resultado >= 2650 -> "10"
                resultado >= 2525 -> "9.5"
                resultado >= 2400 -> "9"
                resultado >= 2300 -> "8.5"
                resultado >= 2200 -> "8"
                resultado >= 2150 -> "7.5"
                resultado >= 2100 -> "7"
                resultado >= 2050 -> "6.5"
                resultado >= 2000 -> "6"
                resultado >= 1950 -> "5.5"
                resultado >= 1900 -> "5"
                resultado >= 1850 -> "4.5"
                resultado >= 1800 -> "4"
                resultado >= 1750 -> "3.5"
                resultado >= 1700 -> "3"
                resultado >= 1650 -> "2.5"
                resultado >= 1600 -> "2"
                else -> "N/A"
            }
            15 -> when {
                resultado >= 2750 -> "10"
                resultado >= 2625 -> "9.5"
                resultado >= 2500 -> "9"
                resultado >= 2400 -> "8.5"
                resultado >= 2300 -> "8"
                resultado >= 2250 -> "7.5"
                resultado >= 2200 -> "7"
                resultado >= 2150 -> "6.5"
                resultado >= 2100 -> "6"
                resultado >= 2050 -> "5.5"
                resultado >= 2000 -> "5"
                resultado >= 1950 -> "4.5"
                resultado >= 1900 -> "4"
                resultado >= 1850 -> "3.5"
                resultado >= 1800 -> "3"
                resultado >= 1750 -> "2.5"
                resultado >= 1700 -> "2"
                else -> "N/A"
            }
            16 -> when {
                resultado >= 2800 -> "10"
                resultado >= 2650 -> "9.5"
                resultado >= 2500 -> "9"
                resultado >= 2450 -> "8.5"
                resultado >= 2400 -> "8"
                resultado >= 2350 -> "7.5"
                resultado >= 2300 -> "7"
                resultado >= 2250 -> "6.5"
                resultado >= 2200 -> "6"
                resultado >= 2150 -> "5.5"
                resultado >= 2100 -> "5"
                resultado >= 2050 -> "4.5"
                resultado >= 2000 -> "4"
                resultado >= 1950 -> "3.5"
                resultado >= 1900 -> "3"
                resultado >= 1850 -> "2.5"
                resultado >= 1800 -> "2"
                else -> "N/A"
            }
            else -> "N/A"
        }

        "Chica" -> when (edad) {
            12 -> when {
                resultado >= 2200 -> "10"
                resultado >= 2100 -> "9.5"
                resultado >= 2000 -> "9"
                resultado >= 1900 -> "8.5"
                resultado >= 1800 -> "8"
                resultado >= 1750 -> "7.5"
                resultado >= 1700 -> "7"
                resultado >= 1550 -> "6.5"
                resultado >= 1600 -> "6"
                resultado >= 1550 -> "5.5"
                resultado >= 1500 -> "5"
                resultado >= 1450 -> "4.5"
                resultado >= 1400 -> "4"
                resultado >= 1350 -> "3.5"
                resultado >= 1300 -> "3"
                resultado >= 1250 -> "2.5"
                resultado >= 1200 -> "2"
                else -> "N/A"
            }
            13 -> when {
                resultado >= 2100 -> "10"
                resultado >= 2050 -> "9.5"
                resultado >= 2000 -> "9"
                resultado >= 1950 -> "8.5"
                resultado >= 1900 -> "8"
                resultado >= 1850 -> "7.5"
                resultado >= 1800 -> "7"
                resultado >= 1750 -> "6.5"
                resultado >= 1700 -> "6"
                resultado >= 1650 -> "5.5"
                resultado >= 1600 -> "5"
                resultado >= 1550 -> "4.5"
                resultado >= 1500 -> "4"
                resultado >= 1450 -> "3.5"
                resultado >= 1400 -> "3"
                resultado >= 1350 -> "2.5"
                resultado >= 1300 -> "2"
                else -> "N/A"
            }
            14 -> when {
                resultado >= 2200 -> "10"
                resultado >= 2050 -> "9.5"
                resultado >= 1900 -> "9"
                resultado >= 1850 -> "8.5"
                resultado >= 1800 -> "8"
                resultado >= 1750 -> "7.5"
                resultado >= 1700 -> "7"
                resultado >= 1650 -> "6.5"
                resultado >= 1600 -> "6"
                resultado >= 1550 -> "5.5"
                resultado >= 1500 -> "5"
                resultado >= 1450 -> "4.5"
                resultado >= 1400 -> "4"
                resultado >= 1350 -> "3.5"
                resultado >= 1300 -> "3"
                resultado >= 1250 -> "2.5"
                resultado >= 1200 -> "2"
                else -> "N/A"
            }
            15 -> when {
                resultado >= 2250 -> "10"
                resultado >= 2150 -> "9.5"
                resultado >= 2050 -> "9"
                resultado >= 1975 -> "8.5"
                resultado >= 1900 -> "8"
                resultado >= 1850 -> "7.5"
                resultado >= 1800 -> "7"
                resultado >= 1750 -> "6.5"
                resultado >= 1700 -> "6"
                resultado >= 1650 -> "5.5"
                resultado >= 1600 -> "5"
                resultado >= 1550 -> "4.5"
                resultado >= 1500 -> "4"
                resultado >= 1450 -> "3.5"
                resultado >= 1400 -> "3"
                resultado >= 1350 -> "2.5"
                resultado >= 1300 -> "2"
                else -> "N/A"
            }
            16 -> when {
                resultado >= 2300 -> "10"
                resultado >= 2200 -> "9.5"
                resultado >= 2100 -> "9"
                resultado >= 2025 -> "8.5"
                resultado >= 1950 -> "8"
                resultado >= 1900 -> "7.5"
                resultado >= 1850 -> "7"
                resultado >= 1800 -> "6.5"
                resultado >= 1750 -> "6"
                resultado >= 1700 -> "5.5"
                resultado >= 1650 -> "5"
                resultado >= 1600 -> "4.5"
                resultado >= 1550 -> "4"
                resultado >= 1500 -> "3.5"
                resultado >= 1450 -> "3"
                resultado >= 1400 -> "2.5"
                resultado >= 1350 -> "2"
                else -> "N/A"
            }
            else -> "N/A"
        }
        else -> "N/A"
    }
}


fun calcularNotaVelocidad(resultado: Float, edad: Int, sexo: String): String {
    return when (sexo) {
        "Chico" -> when (edad) {
            14 -> when {
                resultado >= 15.6 -> "2"
                resultado >= 15.4 -> "2.5"
                resultado >= 15.2 -> "3"
                resultado >= 15.0 -> "3.5"
                resultado >= 14.6 -> "4"
                resultado >= 14.4 -> "4.5"
                resultado >= 14.2 -> "5"
                resultado >= 14.0 -> "5.5"
                resultado >= 13.8 -> "6"
                resultado >= 13.6 -> "6.5"
                resultado >= 13.4 -> "7"
                resultado >= 13.2 -> "7.5"
                resultado >= 13.0 -> "8"
                resultado >= 12.8 -> "8.5"
                resultado >= 12.6 -> "9"
                resultado >= 11.0 -> "10"
                else -> "N/A"
            }
            15 -> when {
                resultado >= 15.3 -> "2"
                resultado >= 15.1 -> "2.5"
                resultado >= 14.9 -> "3"
                resultado >= 14.7 -> "3.5"
                resultado >= 14.5 -> "4"
                resultado >= 14.3 -> "4.5"
                resultado >= 14.1 -> "5"
                resultado >= 13.9 -> "5.5"
                resultado >= 13.7 -> "6"
                resultado >= 13.5 -> "6.5"
                resultado >= 13.3 -> "7"
                resultado >= 13.1 -> "7.5"
                resultado >= 12.9 -> "8"
                resultado >= 12.7 -> "8.5"
                resultado >= 12.5 -> "9"
                resultado >= 12.3 -> "9.5"
                resultado >= 11.0 -> "10"
                else -> "N/A"
            }
            16 -> when {
                resultado >= 15.0 -> "2"
                resultado >= 14.8 -> "2.5"
                resultado >= 14.6 -> "3"
                resultado >= 14.4 -> "3.5"
                resultado >= 14.2 -> "4"
                resultado >= 14.0 -> "4.5"
                resultado >= 13.8 -> "5"
                resultado >= 13.6 -> "5.5"
                resultado >= 13.4 -> "6"
                resultado >= 13.2 -> "6.5"
                resultado >= 13.0 -> "7"
                resultado >= 12.8 -> "7.5"
                resultado >= 12.6 -> "8"
                resultado >= 12.4 -> "8.5"
                resultado >= 12.2 -> "9"
                resultado >= 12.0 -> "9.5"
                resultado >= 11.0 -> "10"
                else -> "N/A"
            }
            else -> "N/A"
        }
        "Chica" -> when (edad) {
            14 -> when {
                resultado >= 16.4 -> "2"
                resultado >= 16.2 -> "2.5"
                resultado >= 16.0 -> "3"
                resultado >= 15.8 -> "3.5"
                resultado >= 15.6 -> "4"
                resultado >= 15.4 -> "4.5"
                resultado >= 15.2 -> "5"
                resultado >= 15.0 -> "5.5"
                resultado >= 14.8 -> "6"
                resultado >= 14.6 -> "6.5"
                resultado >= 14.4 -> "7"
                resultado >= 14.2 -> "7.5"
                resultado >= 14.0 -> "8"
                resultado >= 13.8 -> "8.5"
                resultado >= 13.6 -> "9"
                resultado >= 13.4 -> "9.5"
                resultado >= 11.0 -> "10"
                else -> "N/A"
            }
            15 -> when {
                resultado >= 16.1 -> "2"
                resultado >= 15.9 -> "2.5"
                resultado >= 15.7 -> "3"
                resultado >= 15.5 -> "3.5"
                resultado >= 15.3 -> "4"
                resultado >= 15.1 -> "4.5"
                resultado >= 14.9 -> "5"
                resultado >= 14.7 -> "5.5"
                resultado >= 14.5 -> "6"
                resultado >= 14.3 -> "6.5"
                resultado >= 14.1 -> "7"
                resultado >= 13.9 -> "7.5"
                resultado >= 13.7 -> "8"
                resultado >= 13.5 -> "8.5"
                resultado >= 13.3 -> "9"
                resultado >= 13.1 -> "9.5"
                resultado >= 11.0 -> "10"
                else -> "N/A"
            }
            16 -> when {
                resultado >= 15.8 -> "2"
                resultado >= 15.6 -> "2.5"
                resultado >= 15.4 -> "3"
                resultado >= 15.2 -> "3.5"
                resultado >= 15.0 -> "4"
                resultado >= 14.8 -> "4.5"
                resultado >= 14.6 -> "5"
                resultado >= 14.4 -> "5.5"
                resultado >= 14.2 -> "6"
                resultado >= 14.0 -> "6.5"
                resultado >= 13.8 -> "7"
                resultado >= 13.6 -> "7.5"
                resultado >= 13.4 -> "8"
                resultado >= 13.2 -> "8.5"
                resultado >= 13.0 -> "9"
                resultado >= 12.8 -> "9.5"
                resultado >= 11.0 -> "10"
                else -> "N/A"
            }
            else -> "N/A"
        }
        else -> "N/A"
    }
}


fun calcularNotaLanzamiento(resultado: Float, edad: Int, sexo: String): String {
    return when (sexo) {
        "Chico" -> when (edad) {
            15 -> when {
                resultado >= 8.50 -> "10"
                resultado >= 8.20 -> "9.5"
                resultado >= 7.90 -> "9"
                resultado >= 7.60 -> "8.5"
                resultado >= 7.30 -> "8"
                resultado >= 7.00 -> "7.5"
                resultado >= 6.70 -> "7"
                resultado >= 6.40 -> "6.5"
                resultado >= 6.10 -> "6"
                resultado >= 5.80 -> "5.5"
                resultado >= 5.50 -> "5"
                resultado >= 5.20 -> "4.5"
                resultado >= 5.00 -> "4"
                resultado >= 4.70 -> "3.5"
                resultado >= 4.40 -> "3"
                resultado >= 4.10 -> "2.5"
                resultado >= 3.80 -> "2"
                else -> "N/A"
            }
            16 -> when {
                resultado >= 8.70 -> "10"
                resultado >= 8.40 -> "9.5"
                resultado >= 8.10 -> "9"
                resultado >= 7.80 -> "8.5"
                resultado >= 7.50 -> "8"
                resultado >= 7.20 -> "7.5"
                resultado >= 6.90 -> "7"
                resultado >= 6.60 -> "6.5"
                resultado >= 6.30 -> "6"
                resultado >= 6.10 -> "5.5"
                resultado >= 5.90 -> "5"
                resultado >= 5.70 -> "4.5"
                resultado >= 5.50 -> "4"
                resultado >= 5.30 -> "3.5"
                resultado >= 5.10 -> "3"
                resultado >= 4.90 -> "2.5"
                resultado >= 4.70 -> "2"
                else -> "N/A"
            }
            else -> "N/A"
        }

        "Chica" -> when (edad) {
            15 -> when {
                resultado >= 8.50 -> "10"
                resultado >= 8.20 -> "9.5"
                resultado >= 7.90 -> "9"
                resultado >= 7.60 -> "8.5"
                resultado >= 7.30 -> "8"
                resultado >= 7.00 -> "7.5"
                resultado >= 6.70 -> "7"
                resultado >= 6.40 -> "6.5"
                resultado >= 6.10 -> "6"
                resultado >= 5.80 -> "5.5"
                resultado >= 5.50 -> "5"
                resultado >= 5.20 -> "4.5"
                resultado >= 5.00 -> "4"
                resultado >= 4.70 -> "3.5"
                resultado >= 4.40 -> "3"
                resultado >= 4.10 -> "2.5"
                resultado >= 3.80 -> "2"
                else -> "N/A"
            }
            16 -> when {
                resultado >= 8.70 -> "10"
                resultado >= 8.40 -> "9.5"
                resultado >= 8.10 -> "9"
                resultado >= 7.80 -> "8.5"
                resultado >= 7.50 -> "8"
                resultado >= 7.20 -> "7.5"
                resultado >= 6.90 -> "7"
                resultado >= 6.60 -> "6.5"
                resultado >= 6.30 -> "6"
                resultado >= 6.10 -> "5.5"
                resultado >= 5.90 -> "5"
                resultado >= 5.70 -> "4.5"
                resultado >= 5.50 -> "4"
                resultado >= 5.30 -> "3.5"
                resultado >= 5.10 -> "3"
                resultado >= 4.90 -> "2.5"
                resultado >= 4.70 -> "2"
                else -> "N/A"
            }
            else -> "N/A"
        }
        else -> "N/A"
    }
}